###Assignment no 1 




###1. In the below elements which of them are values or an expression? eg:- values can be integer or string and expressions will be mathematical operators.

*,'hello', -87.8,-,/,+,6

***Answer*** : - In the above question total number of operators are '4' and total number of expressions are '3' 

1. '*' is an Arithmatic (multiplication) operator
2. 'hello' is value of string data type 
3. '-87.8' is value of (negative) integer data type
4. '-' is an Arithmatic (subtraction) operator 
5. '/' is an Arithmatic (division) operator 
6. '+' is an Arithmatic (Addition) operator 
7. '6' is value of (positive) integer data type

###2. What is the difference between string and variable?

***Answer*** : - **Variable** :- a variable is a named location used to store data in memory.Data can be integer, float, string type. We can declare variables by writting the variable name and assign '=' sign to store value into it demonstrated as follows:

In [2]:
x = 4              # x is a variable which stores integer value 
y = "shruti"       # y is a variable which stores string data type value 
z = 3.56           # z is a variable which stores float value

**String** :- Strings are sequence of characters or alphabets. It is bouned in "" and in the variable, information can be stored.It demonstrated as follows:

In [3]:
a = "Hello World!"       # a is a string which stores sequence of characters (string)

###3. Describe three different data types.

***Answer*** :- In python total three data types are there as follows : 


1. ***Integer*** :- This data types stores whole numbers and it can be positive or negative.
2. ***Floats*** :- This data types comes with decimal points with fractional components. It stores real numbers values.
3. ***String*** :- This dta types store sequence of characters or alphabets bounded by ""

These all data types are demonstrated as follows:

In [6]:
a = 33            # a is a integer which stores positive value
b = -10           # b is a integer which stores negative value 

print(a)
print(b)

33
-10

In [7]:
x = -45.0          # x is a float data type which stores negative value 
y = 50.7           # y is a float data type which stores positive value

print(x)
print(y)

-45.0
50.7

In [8]:
s = "welcome to python!"        # s variable stores string data types which is sequence of charachers

print(s)

welcome to python!

###4. What is an expression made up of? What do all expressions do?

***Answer*** :- An ***expression*** is made up of different types of variables, values followed by different types of operators. In python expression is getting evaluated if the expression is error free then it displays the output as follows:

In [9]:
a = 4 + 15 *2 - 34     # It is an expression which returns result of evaluation
print(a)

0

###5. This assignment statements, like spam = 10. What is the difference between an expression and a statement?

***Answer*** :-   A ***statement*** in Python is an instruction that the Python interpreter can read and execute. A statement can store some values.When the statement is getting evaluated t becomes an expression. ***Expression*** always displays result of input values given by statements. After evaluating expression value does not changes while we can change the value of statement by making some changes into it. Expression reslut can be stored in statement for execution.In spam =10 it is a statement where only value '10' can be stored cannot evaluate. in following example statement and expression are given:

In [11]:
a = 15            # a is a statement which stores value 15
b = a + 2         # b is an expression which can be evaluated 

print(a)
print(b)

15
17

###6. After running the following code, what does the variable bacon contain?
bacon = 22

bacon + 1

***Answer*** :-  After execution of above code variable 'bacon' displays 23 as it will update the value which is followed by expression.

In [12]:
bacon = 22       
bacon + 1        # 'bacon' updates value after evaluation of expression and returns value

23

###7. What should the values of the following two terms be?

'spam' + 'spamspam'

'spam' * 3


***Answer*** :- In the first term, 'spam'+'spamspam' use of additin arithmetic operator on string has performed to concatinate. Simillarly, in second term 'spam' * 3  use of multiplication operator on string is performed which returns same result as previous term. Let us see following expression :

In [1]:
'spam' + 'spamspam'

'spamspamspam'

In [2]:
'spam' * 3

'spamspamspam'

###8. Why is eggs a valid variable name while 100 is invalid?

***Answer*** :-  Python is a case-sensitive language for eg;

 var_a,

 Var_a,

 var_A 

 these are three different variables. Variable name must start with a letter or the underscore character, but not with a digit. 
In the given statement 'egg' fulfills all the above conditions therefore, it is a valid variable name 100 is not.

###9. What three functions can be used to get the integer, floating-point number, or string version of a value?

***Answer*** :-  To get the data type, 
1. int()
2. float()
3. str()

these functions are used accordingly.In the following example it is demonstrated:

In [10]:
var1 = 5

var_int = int(var1)
print("Integer Value is:",var_int, type(var_int))


var2 = 3.0 

Var_float = float(var2)
print("Float Value is:" ,Var_float, type(Var_float))


var3 = "Welcome to  python"

vaar_string = str(var3)
print("String Value is:" ,vaar_string, type(vaar_string))

Integer Value is: 5 <class 'int'>
Float Value is: 3.0 <class 'float'>
String Value is: Welcome to  python <class 'str'>

###10. Why does this expression cause an error? How can you fix it?

'I have eaten ' + 99 + ' burritos.'

In [11]:

'I have eaten ' + 99 + ' burritos.'

TypeError: ignored

***Answer*** :- In the above expression 99 is a integer value which cannot concatinate with string data type. This expression needs to be convert in string type to get correct result demonstrated as follows:

In [13]:
  # Expression needs to be convert in string data type by using following method

'I have eaten' + '99' + ' burritos'      # 99 is used as string data type to concatinate

'I have eaten99burritos'